		var userdata;
		var UserPasswd;
		var ScenarioID;
		var UserMoney;
		var UserDialogCollection;
		var UserSaveTimeCollection;
		var DialogID;
		var DialogSet;
		var UserID;
		var UserAccount;
		var Character;
		var CharacterName;
		var BGM;
		var Sound;
		var UserLove;
		var BGpath;
		
		var GlobalBGM;//目前播放的BGM
		var GlobalSound;//目前播放的Sound